contentColumnType: boolean
fieldGroup: fdec3457-ed33-47af-b139-c64299d91569 # Bron Detail
handle: switchHate
instructions: ''
name: 'Switch Hate'
searchable: false
settings:
  default: false
  offLabel: 'Hate crime/hate speech worden niet expliciet opgenomen'
  onLabel: 'Hate crime/hate speech worden expliciet opgenomen'
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
